apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: blog-app-pipeline-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: blog-app-pipeline
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials 