apiVersion: v1
kind: Secret
metadata:
  name: blog-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/yourusername/blog-app-gitops.git
  username: github-username
  password: github-token 